project 'First-Weex.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'First-Weex' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'WeexSDK', '0.9.5'   ## 建议使用WeexSDK新版本

end
